#!/bin/bash

tmux new-session -d -s $WS_SESSION -n code
tmux send-keys -t $WS_SESSION "vim code.py" ^m
tmux split-window -h
tmux send-keys -t $WS_SESSION "python3 code.py" ^m
tmux attach -t $WS_SESSION
