#!/bin/bash

tmux new-session -d -s $WS_SESSION -n code
tmux send-keys -t $WS_SESSION "vim code.c" ^m
tmux split-window -h
tmux send-keys -t $WS_SESSION "clear && gcc code.c && ./a.out" ^m
tmux attach -t $WS_SESSION
