#!/bin/bash

tmux new-session -d -s $WS_SESSION -n code
tmux send-keys -t $WS_SESSION "vim code.rs" ^m
tmux split-window -h
tmux send-keys -t $WS_SESSION "clear && rustc code.rs && ./code" ^m
tmux attach -t $WS_SESSION
