#!/bin/bash

tmux new-session -d -s $WS_SESSION -n code
tmux send-keys -t $WS_SESSION "vim code.asm" ^m
tmux split-window -h
tmux send-keys -t $WS_SESSION "clear && as code.asm -o code.o && ld code.o -o code && ./code; echo $?" ^m
tmux attach -t $WS_SESSION
